/**
 * Shellfish SSH Integration
 * Integration with Shellfish iOS/iPadOS SSH client
 * https://secureshellfish.app/
 */

import type { IntegrationConfig } from '../manager';

export interface ShellfishServer {
  id: string;
  name: string;
  hostname: string;
  port: number;
  username: string;
  authMethod: 'password' | 'key' | 'agent';
  keyName?: string;
  jumpHost?: string;
  localForwards?: ShellfishPortForward[];
  remoteForwards?: ShellfishPortForward[];
  tags?: string[];
}

export interface ShellfishPortForward {
  localPort: number;
  remoteHost: string;
  remotePort: number;
}

export interface ShellfishFile {
  path: string;
  name: string;
  isDirectory: boolean;
  size: number;
  modified: string;
  permissions: string;
}

export interface ShellfishConfig extends IntegrationConfig {
  servers?: ShellfishServer[];
  defaultUsername?: string;
  defaultKeyPath?: string;
}

/**
 * Shellfish integration for managing SSH connections from iOS/iPadOS
 * Generates x-callback-url schemes and SSH config
 */
export class ShellfishIntegration {
  private config: ShellfishConfig;
  private servers: Map<string, ShellfishServer> = new Map();

  constructor(config: ShellfishConfig) {
    this.config = config;

    // Initialize default BlackRoad OS servers
    this.initializeDefaultServers();
  }

  private initializeDefaultServers(): void {
    const defaultServers: ShellfishServer[] = [
      {
        id: 'blackroad-codex',
        name: 'BlackRoad Codex',
        hostname: 'codex.blackroad.io',
        port: 22,
        username: 'deploy',
        authMethod: 'key',
        keyName: 'blackroad_deploy',
        tags: ['production', 'api'],
      },
      {
        id: 'blackroad-droplet',
        name: 'BlackRoad Droplet',
        hostname: '159.65.43.12',
        port: 22,
        username: 'root',
        authMethod: 'key',
        keyName: 'blackroad_key',
        tags: ['production', 'digitalocean'],
      },
      {
        id: 'lucidia-pi',
        name: 'Lucidia Raspberry Pi',
        hostname: '192.168.4.38',
        port: 22,
        username: 'pi',
        authMethod: 'key',
        keyName: 'lucidia_pi',
        tags: ['edge', 'raspberry-pi', 'sentience'],
      },
      {
        id: 'blackroad-pi',
        name: 'BlackRoad Raspberry Pi',
        hostname: '192.168.4.64',
        port: 22,
        username: 'pi',
        authMethod: 'key',
        keyName: 'blackroad_pi',
        tags: ['edge', 'raspberry-pi'],
      },
      {
        id: 'mystery-pi',
        name: 'Mystery Pi',
        hostname: '192.168.4.49',
        port: 22,
        username: 'pi',
        authMethod: 'key',
        keyName: 'mystery_pi',
        tags: ['edge', 'raspberry-pi', 'experimental'],
      },
    ];

    for (const server of defaultServers) {
      this.servers.set(server.id, server);
    }
  }

  /**
   * Generate Shellfish x-callback-url for connecting to a server
   */
  generateCallbackUrl(serverId: string): string {
    const server = this.servers.get(serverId);
    if (!server) {
      throw new Error(`Server ${serverId} not found`);
    }

    const params = new URLSearchParams({
      host: server.hostname,
      port: String(server.port),
      user: server.username,
    });

    if (server.keyName) {
      params.set('key', server.keyName);
    }

    return `shellfish://connect?${params.toString()}`;
  }

  /**
   * Generate SSH config block for a server
   */
  generateSSHConfig(serverId: string): string {
    const server = this.servers.get(serverId);
    if (!server) {
      throw new Error(`Server ${serverId} not found`);
    }

    let config = `Host ${server.name.toLowerCase().replace(/\s+/g, '-')}
    HostName ${server.hostname}
    Port ${server.port}
    User ${server.username}`;

    if (server.authMethod === 'key' && server.keyName) {
      config += `\n    IdentityFile ~/.ssh/${server.keyName}`;
    }

    if (server.jumpHost) {
      config += `\n    ProxyJump ${server.jumpHost}`;
    }

    if (server.localForwards) {
      for (const forward of server.localForwards) {
        config += `\n    LocalForward ${forward.localPort} ${forward.remoteHost}:${forward.remotePort}`;
      }
    }

    if (server.remoteForwards) {
      for (const forward of server.remoteForwards) {
        config += `\n    RemoteForward ${forward.localPort} ${forward.remoteHost}:${forward.remotePort}`;
      }
    }

    return config;
  }

  /**
   * Generate complete SSH config for all servers
   */
  generateAllSSHConfigs(): string {
    const configs: string[] = [
      '# BlackRoad OS SSH Configuration',
      '# Generated by blackroad-os-api-gateway',
      '# Copy to ~/.ssh/config',
      '',
    ];

    for (const serverId of this.servers.keys()) {
      configs.push(this.generateSSHConfig(serverId));
      configs.push('');
    }

    return configs.join('\n');
  }

  /**
   * Add a new server
   */
  addServer(server: ShellfishServer): void {
    this.servers.set(server.id, server);
  }

  /**
   * Get all servers
   */
  getServers(): ShellfishServer[] {
    return Array.from(this.servers.values());
  }

  /**
   * Get servers by tag
   */
  getServersByTag(tag: string): ShellfishServer[] {
    return Array.from(this.servers.values()).filter(
      (server) => server.tags?.includes(tag)
    );
  }

  /**
   * Generate deployment script for a server
   */
  generateDeployScript(serverId: string, service: string): string {
    const server = this.servers.get(serverId);
    if (!server) {
      throw new Error(`Server ${serverId} not found`);
    }

    return `#!/bin/bash
# BlackRoad OS Deployment Script
# Server: ${server.name} (${server.hostname})
# Service: ${service}

set -e

echo "Deploying ${service} to ${server.name}..."

# Pull latest changes
cd /opt/blackroad/${service}
git pull origin main

# Build and restart
if [ -f "docker-compose.yml" ]; then
    docker-compose build
    docker-compose up -d
elif [ -f "Dockerfile" ]; then
    docker build -t blackroad/${service}:latest .
    docker stop ${service} || true
    docker rm ${service} || true
    docker run -d --name ${service} --restart unless-stopped blackroad/${service}:latest
elif [ -f "package.json" ]; then
    npm install
    npm run build
    pm2 restart ${service} || pm2 start npm --name ${service} -- start
fi

echo "Deployment complete!"
`;
  }

  async healthCheck(): Promise<boolean> {
    return this.config.enabled && this.servers.size > 0;
  }
}

export async function initShellfish(config: ShellfishConfig): Promise<boolean> {
  const shellfish = new ShellfishIntegration(config);
  return shellfish.healthCheck();
}

export function shellfishHealthCheck(config: ShellfishConfig): () => Promise<boolean> {
  const shellfish = new ShellfishIntegration(config);
  return () => shellfish.healthCheck();
}
